# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "pwills.com"# no title necessary!
email: peter@pwills.com
url: "http://www.pwills.com" # the base hostname & protocol for your site, e.g. http://example.com


include:
  - _pages
exclude:
  - TODO.md
  - README.md


paginate: 10 # amount of posts to show
paginate_path: /page:num/


plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
# remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
  
# settings for author profile
author:
  name   : "Peter Wills"
  avatar : "/assets/images/headshot.jpg"
  bio    : "Math, modeling, & machine learning. Make data analysis rigorous again!"
  location: "Boulder, CO"
  github : peterewills
  linkedin: peterewills
  facebook: peter.wills.568
  email  : peter@pwills.com

# these show up everywhere at the moment.
defaults:
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      title: " "
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: true
  - scope:
      path: ""
      type: research
    values:
      header:
        overlay_image: /assets/images/chalkboard.jpg
        caption: "Photo credit: [**Roman Mager**](https://www.unsplash.com)"
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "research"
  - scope:
      path: ""
      type: projects
    values:
      header:
        overlay_image: /assets/images/tools.jpg
        caption: "Photo credit: [**Ricky Kharawala**](https://unsplash.com)"
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "projects"

# collections
collections:
  research:
    output: true
  projects:
    output: true
