# Configs for pwills.com

title: "pwills.com"
name: "Peter Wills"
email: peter@pwills.com
url: "http://www.pwills.com"
repository: "peterewills/peterewills.github.io"

include:
  - _pages
  - assets
exclude:
  - TODO.md
  - README.md

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
  
# settings for author profile
author:
  name   : "Peter Wills"
  avatar : "/assets/images/headshot.jpg"
  bio    : "Math, modeling, & machine learning. Make data analysis rigorous again!"
  location: "Boulder, CO"
  github : peterewills
  linkedin: peterewills
  facebook: peter.wills.568
  email  : peter@pwills.com

# pagination for home page
paginate: 5 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # for all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      title: " "
  # for posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: true
  # for collection "research"
  - scope:
      path: ""
      type: research
    values:
      header:
        overlay_image: /assets/images/chalkboard.jpg
        caption: "Photo credit: [**Roman Mager**](https://www.unsplash.com)"
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "research"
  # for collection "projects"
  - scope:
      path: ""
      type: projects
    values:
      header:
        overlay_image: /assets/images/tools.jpg
        caption: "Photo credit: [**Ricky Kharawala**](https://unsplash.com)"
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "projects"

# collections
collections:
  research:
    output: true
  projects:
    output: true
